### ISSUE TITLE
Fix the bug(s) in converting regions to ellipses

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-python#22]
Using DetectorExample notebook and prints inside the conversion functions in helpers.py 2 bugs we discovered:

1. Some regions (contours) are not converted to ellipses. For example, on the images displayed as result of detection (cell 5), one can see 2 protrusions, but only 1 is converted to ellipse. Or there are 8 holes, but only 7 are converted. BUG: some regions are missed. Something to do with the contour's hierarchy?
2. The very first region (0), of type "indentation" has a negative value of the x coordinate as output of cv2.fitEllipse (the polynomial features are 0 : [ -5.63442383e+01   1.42432800e+02   3.49375491e-06  -1.73489827e-20   1.45158949e-04   3.00000000e+00], see first line of the output of cell 7). BUG: center of a region's coordinates cannot be negative. Un-commenting the prints in binary_mask2ellipse_features_single (helpers.py) one can see that the negative x = -56 appears at the very beginning when trying to fit an ellipse to the region (contour), still cell 6.

**Comment by dafnevk** [comment]
Bug 1 is no longer present, I probably solved it when solving #27

**Comment by dafnevk** [comment]
[This article](http://stackoverflow.com/questions/17159964/opencvs-fitellipse-sometimes-returns-completely-wrong-ellipses) on stackoverflow gives some information. It is a bit of an odd (triangular) shape and maybe therefore the fitellipse function doesn't work well. 
What method/algorithm does Matlab use for finding the ellipses?
Is there a way to workaround this problem?

**Comment by dafnevk** [comment]
From the matlab documentation on MajorAxis:

> Returns a scalar that specifies the length (in pixels) of the major axis of the ellipse that has the same normalized second central moments as the region.

**Comment by dafnevk** [comment]
We could use `minAreaRect` instead of `fitEllipse`. 
This gives the inscribed ellipse of the minimum enclosed rotaded rectangle. It seems to give reasonable results, (but probably different than in Matlab).
