### ISSUE TITLE
Verify the detector finds the same saliency masks like the MATLAB code: gray image

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-python#23]
The MATLAB regions masks have not been transferred to the new repo from the TestData folder. I'll put them in the new repo.

**Comment by dafnevk** [comment]
I think we should test the data driven binarization first seperately. I will make an issue for this.

**Comment by dafnevk** [comment]
@elboyran 
Can you refer to the exact parameters used for the regions detected in 
SalientDetector-python/tests/images/Color/  and SalientDetector-python/tests/images/Gray/ ?

**Comment by elboyran** [comment]
For the DMSR(A) the parameters were:
SE_size_factor = 0.02;
Area_factor_very_large = 0.01;
Area_factor_large = 0.001;
lambda_factor = 3;
num_levels = 255;
offset = 80;
otsu_only = false;
conn = 8;
weight_all = 0.33;
weight_large = 0.33;
weight_very_large = 0.33;
saliency_type = [1 1 1 1];/ saliency_type = [1 1 0 0];

For the MSSR(A):
saliency_types = [1 1 1 1];/ saliency_type = [1 1 0 0];
SE_size_factor = 0.02;
Area_factor = 0.03;
num_levels = 20;
thresh = 0.6;
thresh_type = 's';

**Comment by dafnevk** [comment]
There is a difference for the holes and images, and I think it has to do with connectivity.
In OpenCV, for find_contours the connectivity is hardcoded to be 8 (http://stackoverflow.com/questions/17001838/findcontours-for-blob-finding)
In the Matlab code, there is a hardcoded connectivity of 4 in the bwareaopen:
https://github.com/NLeSC/SalientDetector-matlab/blob/master/Generic/binary_detector.m#L161

**Comment by elboyran** [comment]
For which detectors, tests and images do you get this difference? I can remove the hard-coded number in bwareaopen and we can compare again.

**Comment by elboyran** [comment]
The MATLAB function bwareaopen now uses hard-coded connectivity of 8 as well. Tests pass.
