### ISSUE TITLE
Verify the detector finds the same saliency masks like the MATLAB code: color image

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-python#24]
The MATLAB regions masks have not been transferred to the new repo from the TestData folder. I'll put them in the new repo.

**Comment by elboyran** [comment]
We should find out this before comparing the elliptic regions. Already I see by eye that the detected regions are very different form the MATLAB result, i.e. has high priority. Perhaps different parameters?
Also to be checked in issue #23.

**Comment by dafnevk** [comment]
MSSRA finds quite different regions, see https://github.com/NLeSC/SalientDetector-python/blob/master/Notebooks/Test_MSSRA.ipynb

**Comment by elboyran** [comment]
Maybe we should debug this together step by step in parallel- the Python and MATLAB codes?

**Comment by dafnevk** [comment]
I think that's a good idea.

**Comment by elboyran** [comment]
Hi Dafne,

I have played a bit with the MSSRA detector as continuation to what we did yesterday. Using the same parameters in MATLAB and Python- all like in the Excel sheet, but looking at a single threshold of 125 and step_size of 1, I compared:

- the binarised images at 125- same

- the accumulated (in this case with max value of 1 of course) holes - same

- the accumulated (max 1) islands- difference!
See the notebook https://github.com/NLeSC/SalientDetector-python/blob/master/Notebooks/Test_MSSRA.ipynb
I pushed also the mat files I generated for this simple test.

I hope you can find out why the islands are different.

**Comment by dafnevk** [comment]
Haven't solved this yet, but it does make sense that the MSSRA with only level 125 finds different regions than the DMSRA (even though DMSRA also uses level 125) - because the parameter for lambda_factor etc. are different.

**Comment by dafnevk** [comment]
The difference is already in the binary detector: 
https://github.com/NLeSC/SalientDetector-python/blob/master/Notebooks/Test_Binary_detection_Colorimage.ipynb

**Comment by dafnevk** [comment]
Ah, if I change the connectivity from 4 to 8 the islands are correct for the binary image.
Is the connectivity used for MSSRA indeed 4 (cel F53 in the excel sheet)? Or is there a hardcoded 8 somewhere?

**Comment by elboyran** [comment]
MSSRA debugging: Binarised color image at level 125-> MATLAB results and SE with the parameters for the MSSRA is available.

**Comment by elboyran** [comment]
Yes, it's 4. I just ran the MATLAB with that setting.

**Comment by elboyran** [comment]
Wait! In the MATLAB code t was hard-coded 4, then we changed it to 8 for the DMSR test to pass (or so?) for the area opening. Which one should it be? Parameter?

**Comment by elboyran** [comment]
Look at this commit: https://github.com/NLeSC/SalientDetector-matlab/commit/759e2d1281b0b6946a03d4d981c20155a2370f94

**Comment by dafnevk** [comment]
I don't think that piece of code is the problem - because that is also hardcoded in the python code (well, in the opencv code, but we can't change that).

Ok I'm going to run the test again for the binary image with the results that you generated.

**Comment by dafnevk** [comment]
Ok it's still the case that with connectivity 8, the islands are correct.
With connectivity 4, the islands are incorrect but the protrusions are actually correct.
In both cases, the indentations are incorrect.

**Comment by dafnevk** [comment]
I might have found a possible issue:
in the matlab code, when you call `imfill`, the connectivity is not specified. I think it uses a default connectivity of 4. Can this be changed to the parameterized connectivity?

**Comment by elboyran** [comment]
Yes, it can. Shall we use 8? But then do we repeat all tests?

**Comment by dafnevk** [comment]
So I would:
* Change the imfill so that it uses the parameterized connectivity
* Run all tests again, with the connectivities as specified in the excel sheet

**Comment by dafnevk** [comment]
Although this might not be the actual problem, since the default value in imfill is 4 and for mssra we also used 4. But let's see what happens when we change it.

**Comment by dafnevk** [comment]
OK I think I know. We mixed up the functionalities. 

* `bwareaopen` in matlab corresponds to `_remove_small_elements` in python. In python, we use the parameterized connectivity, in Matlab it is now hardcoded as 8
* `imfill` in matlab corresponds to `_fill_image` in python. In python, we cannot specificy the connectivity (in `findContours`) because it is hardcoded to 8 in opencv. In Matlab, the connectivity is not specified so imfill uses the default value of 4.

In order to make them equivalent, we should do the following in the matlab code:
* use the parameterized connectivity in `bwareaopen`
* use hardcoded connectivity of 8 in `imfill`
* run (unfortunately) all tests again.

**Comment by elboyran** [comment]
I see. OK, I'll work on that and see if I should work on the ellipse saving (I found out we sometimes swap major and minor axes) + conversion later.

**Comment by elboyran** [comment]
Cleaned up all MATLAB results from /tests/features. Forgot to mention the issue in the commit. Will start clean.

**Comment by elboyran** [comment]
MATLAB binary detector code modified. Commit https://github.com/NLeSC/SalientDetector-matlab/commit/370de809f73b571e2ce1e818d6172705115fdc1b

**Comment by elboyran** [comment]
Just to make it clear: the data-driven binarization function in MATLAB (max_connected_component_thresholding) already uses parametrised connectivity for bwareaopen:
https://github.com/NLeSC/SalientDetector-matlab/blob/master/Generic/max_conncomp_thresholding.m#L160

**Comment by elboyran** [comment]
Data-driven binarizaiton is ready.

**Comment by elboyran** [comment]
Binary detection of Binary_all_noise is ready.

**Comment by elboyran** [comment]
Binary detection of Binary_nested is ready.

**Comment by elboyran** [comment]
MSSRA detection on the Color image is ready. 425 regions were found.

**Comment by elboyran** [comment]
DMSRA detection on the Gray-scale images is ready. 625 regions were found.

**Comment by elboyran** [comment]
DMSRA detection on the Color image is ready. 360 regions were found. This is the last test described in the Excel sheet.
