### ISSUE TITLE
Write test for DataDriven binarization

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-python#26]
We should test the DataDriven binarization on a  grey-level image (preferably the same in #23)

@elboyran Can you perform this in Matlab and output the binary image?

**Comment by dafnevk** [comment]
Of course we need to make sure to use the exact same parameters.

**Comment by elboyran** [comment]
For that I should first write a small testing script in MATLAB as I don't have one testing only this functionality.

**Comment by elboyran** [comment]
In MATLAB I binarized with the data-driven approach the image gray.png to produce gray_data_binarization.png with parameters:
SE_size_factor = 0.02;
Area_factor_very_large = 0.01;
Area_factor_large = 0.001;
lambda_factor = 3;
num_levels = 255;
offset = 80;
otsu_only = false;
conn = 8;
weight_all = 0.33;
weight_large = 0.33;
weight_very_large = 0.33;

The computed threshold was 106.

**Comment by dafnevk** [comment]
The threshold found by the python implementation is 105 (see the notebook), so there's a difference of 1 level.
Is the matlab implementation using > or >=? That might explain the difference.

**Comment by dafnevk** [comment]
It seems that in [the matlab code](https://github.com/NLeSC/LargeScaleImaging/blob/master/Software/MATLAB/AfineRegions/Detectors/Generic/max_conncomp_thresholding.m)  `<` and `<=` are still being mixed.
@elboyran could you fix this and generate the results again?

**Comment by elboyran** [comment]
I can, but is this the same issue as 105 instead of 106? The number is found by a formula (true dependent on threshold), and the final result is the final threshold with that number. I'll do it again, but finally we should get both the number and the result the same.

**Comment by dafnevk** [comment]
Strangly, it seems that the binarized image corresponds with no single threshold (according to the cv2 threshold function). See [the notebook](https://github.com/NLeSC/SalientDetector-python/blob/master/Notebooks/Test_Binarizer.ipynb)
It comes closes to threshold level **105** . Because cv2 uses `>` for thresholding.

For comparison it would be best if the matlab code also uses `>` consistently.

**Comment by elboyran** [comment]
Yes, I'll do that.

**Comment by elboyran** [comment]
Ah, I see- it's in line 225. So, maybe final binarization is not correct, but the 106 should be the correct threshold (to compute the CCes > is used and the formula should be the same in both codes).

**Comment by elboyran** [comment]
I committed the binary result of binary_image = gray_image > thresh. I still get thresh = 106.

**Comment by elboyran** [comment]
Another thing which might explain 105 and not 106 is that this being an index of the array containing the values of the number of CC per level, MATLAB counts indices starting at 1, not 0! Would it help to compare the actual function plot?

**Comment by dafnevk** [comment]
That could be a reason...

For my understanding, does that also mean that in Matlab, each pixel has minum value 1 and maxium value 256? (instead of 0 and 255 resp, as in opencv). Because if that's the case, then all levels are indeed shifted by one.

**Comment by elboyran** [comment]
No, in MATLAB gray values are from 0 to 255. In my implementation I ignore the 0 (not sure why). Here are snippets of the code:
% gray levels
min_level =  1; max_level = 255;
...
% init
binary_masks = zeros(nrows,ncols, max_level,'uint8');
    num_cc = zeros(1,max_level);
    num_large_cc = zeros(1,max_level);
    num_very_large_cc = zeros(1,max_level);
    num_combined_cc = zeros(1,max_level);
....
for level = otsu - off: step: otsu + off
        l = fix(level);       
        CC = bwconncomp(binary_masks(:,:,l),connectivity);
  ....
        num_large_cc(l) = ln;
        num_very_large_cc(l) = vln;
    end
    
    % normalize the counts

    [max_num, thresh_all] = max(num_cc(:));
    [max_large_num, thresh_large] = max(num_large_cc(:)); 
    [max_very_large_num, thresh_very_large] = max(num_very_large_cc(:));
    
    norm_num_cc = num_cc/max_num;
    norm_large_num_cc = num_large_cc/max_large_num;
    norm_very_large_num_cc = num_very_large_cc/max_very_large_num;
    

    num_combined_cc = (weight_all*norm_num_cc + ...
        weight_large* norm_large_num_cc+ ...
        weight_very_large*norm_very_large_num_cc);


    [max_combined, thresh] = max(num_combined_cc); <--- Here the final thresh is the index in the array of recorded num of CC where that number is maximum.

**Comment by dafnevk** [comment]
I see where a possible difference may come from. The matlab code does the following:
`binary_filt = bwareaopen(binary, lambda, connectivity);`

This filtering of small elements does currently not happen in the python code, I will change that.

**Comment by dafnevk** [comment]
Actually, this already taken care of in the following line:
`a_nccs[t] = sum(areas > self.lam) ` 

However, there is no filtering of tiny holes (`bwareaopen` of the inverse image) which might be the reason that there is a slightly different binarization.

**Comment by dafnevk** [comment]
The filtering is not the problem, I tested it including filtering of the reverse image, but still returns 105. 

What still bothers me is that the Matlab binarized image corresponds with no single threshold-binarization that I can find.

**Comment by elboyran** [comment]
This is indeed strange. The final binarizaion is really just an >= operation, should be the same no matter of the language/library used.

**Comment by dafnevk** [comment]
I now see that the test image ( [this one](https://github.com/NLeSC/SalientDetector-python/blob/master/tests/images/Gray/gray.png) ) is not really a gray image! So maybe the conversion to gray is already different.
Can we test it on a REAL gray image?

**Comment by elboyran** [comment]
Oh, I see. I think in all test sets only the 'boat sequence' was gray. The one we used for other binarizations. Do you want MATLAB test result for it?

**Comment by dafnevk** [comment]
Sure that's fine.
(Could you also remove then all results for this image?)

**Comment by elboyran** [comment]
OK. I might have time only on Thursday morning though. Hopefully you can do other things by then?

**Comment by elboyran** [comment]
Using the same parameters as above on the gray scale image (boat), I obtained a data-driven binarization. The found threshold is 146. The binary image is committed, I will send also plots by email.

**Comment by dafnevk** [comment]
Could you check what the lamda is that the algorithm used for this picture? 
In my calculations, it should be 27.

**Comment by elboyran** [comment]
Hm. My lambda is 24!

**Comment by elboyran** [comment]
That's the formula in the MATLAB code:
lambda = lambda_factor* fix(SE_size_factor*sqrt(Area/pi))

**Comment by elboyran** [comment]
Area is 578000

**Comment by dafnevk** [comment]
Ah it's the difference between using round (which gives 27) or floor (which gives 24). Anyway, for the eventual binarization it doesn't make much difference.

**Comment by dafnevk** [comment]
Is it possible to output the intermediate results, such as the arrays `norm_very_large_num_cc`, `norm_large_num_cc`, `norm_num_cc` and `num_combined_cc`?
The plots look very similar but it's hard to see if they are the same.

**Comment by elboyran** [comment]
Also, remove the area opening filtering from the MATLAB code and simply count only regions above certain area.

**Comment by elboyran** [comment]
You are working on this one now, right?
