### ISSUE TITLE
Generate MATLAB saliency masks for the DMSRA and MSSRA detectors for the complete process (color -> gray -> binary -> regions)

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-python#30]
Same gray-image as for the binarization tests.

**Comment by elboyran** [comment]
The gray image to be used will be the boat1 image. Cool car wasn't really gray.

**Comment by elboyran** [comment]
Parameters used for the DMSR:
SE_size_factor = 0.02;
Area_factor_very_large = 0.01;
Area_factor_large = 0.001;
lambda_factor = 3;
num_levels = 255;
offset = 80;
otsu_only = false;
conn = 8;
weight_all = 0.33;
weight_large = 0.33;
weight_very_large = 0.33;
saliency_type = [1 1 0 0];

Some computed parameters:
lambda (for the binarization): 24
SE_size = 8
lambda (for DMSR) = 40

**Comment by elboyran** [comment]
Parameters used for MSSRA:

                saliency_types = [1 1 1 1];
                SE_size_factor = 0.02;
                Area_factor = 0.03;
                num_levels = 20;
                thresh = 0.6;
                thresh_type = 's';
Some computed parameters:
SE_size = 8
lambda (for DMSR) = 40

**Comment by elboyran** [comment]
Parameters used for MSSRA:

                saliency_types = [1 1 1 1];
                SE_size_factor = 0.02;
                Area_factor = 0.03;
                num_levels = 20;
                thresh = 0.6;
                thresh_type = 's';
Some computed parameters:
SE_size = 8
lambda (for DMSR) = 40

**Comment by elboyran** [comment]
Committed binary masks for DMSR and MSSRA for the gray_scale image.

**Comment by dafnevk** [comment]
How comes that lambda is larger for the DMSR than for binarization?

**Comment by dafnevk** [comment]
For MSSRA, I'm missing the parameters for lam_factor and connectivity.

**Comment by elboyran** [comment]
For the DMSR (and in fact all other detectors, incl, MSSRA) I have looked at the MATLAB code and found out:
the binary_detector (the base for all other) have hard codded lam_factor (5) and connectivity (4)!
It explains the different lamdba I gave you above.
It's not very nice that the code is not parametric, I'll change that (in a new issue),but maybe you can meanwhile test if you get the same results with these values.

**Comment by elboyran** [comment]
This issue was moved to NLeSC/SalientDetector-matlab#4

**Comment by elboyran** [comment]
moved to the MATLAB repo.
