### ISSUE TITLE
Correct output for Major and minor axes (in `binary_mask2ellipse_features_single`)

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-python#31]

**Comment by dafnevk** [comment]
might also have to adjust `visualize_ellipses`

**Comment by elboyran** [comment]
It was already fixed in the code, but now there is a more generic implementation. Also 2 of the 4 test cases for Ellipses now test the fitEllipse function. Commit https://github.com/NLeSC/SalientDetector-python/commit/b1c51d327a29d0b1c18ad43ccc3ff434008ec029.
