### ISSUE TITLE
Matlab: Go from num_levels to stepsize as user input for Datadriven Binarization

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-python#32]

**Comment by elboyran** [comment]
Did we mean the MATLAB code?

**Comment by elboyran** [comment]
Is this issue still relevant? I see that the DatadrivenBinarizer class in binarisation.py has num_levels are input, not stepsize. Or is the idea to make them both with stepsize?

**Comment by dafnevk** [comment]
It's indeed the idea to both make them stepsize, because num_levels doesn't make so much sense if the range is not from 0 to 255.

**Comment by elboyran** [comment]
The MATLAB code now uses step_size instead of num_levels.
Commit: https://github.com/NLeSC/LargeScaleImaging/commit/4a603bbc445a83751efa7cef9e8aba0466888716

**Comment by elboyran** [comment]
This issue was moved to NLeSC/SalientDetector-matlab#1

**Comment by elboyran** [comment]
moved to the matlab repo.
