### ISSUE TITLE
Fix Test_detection Notebook

### ISSUE THREAD

**Issue by elboyran** [NLeSC/SalientDetector-python#47]
The MATLAB -produced Gray_scale_mssraregions.mat is missing, so the notebook doesn't finish.

**Comment by elboyran** [comment]
I am puzzled about this notebook, the parameters are not according to our Excel sheet.

**Comment by dafnevk** [comment]
It was just never updated since we changed the connectivity things. I will update it and make another issue to check all notebooks.

**Comment by elboyran** [comment]
OK. I have ran all other Notebooks today and they were fine except another one, which I fixed.

**Comment by dafnevk** [comment]
I removed this notebook because I think it's redundant with the test_MSSRA and test_DMSR notebooks.
