### ISSUE TITLE
Write function to output both the polynomial and standard ellipse parameters into a text file 

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-python#5]
@dafnevk commented on [Thu Mar 24 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21)

In order to evaluate the quality of the salient regions, we need to output the salient regions as files containing the coordinates and parameter of the corresponding ellipses.
Part of the code (see comments) should be equivalent to the matlab code in binary_mask2features.m.

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203320041)

Write a helper function  which converts axis lengths and angle to polynomial coefficients. The code should be equivalent to conversion_ellipse.m

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203385625)

Write a helper function binary_mask2ellipse_features which computes the ellipse features (coefficients) from a binary mask of 1 region type (holes|islands|indentations|protrusions). This code should be equivalent to the matlab code in binary_mask2features.m. 

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203397432)

cv2.connectedComponentsWithStats doesn't give enough statistics needed for the region to ellipse representation, e.g. no axis length or orientation. We might need scikit-image for that :-(

---

@dafnevk commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203398438)

I also came across the function [fitellipse](http://docs.opencv.org/3.0-beta/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#fitellipse) , is that of any help?

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203399982)

Not exactly. We actually don't need the ellipse itself, but rather some measurements of  the region, namely defined as:
'MajorAxisLength'	Returns a scalar that specifies the length (in pixels) of the major axis of the ellipse that has the same normalized second central moments as the region.	
'MinorAxisLength'	Returns a scalar that specifies the length (in pixels) of the minor axis of the ellipse that has the same normalized second central moments as the region.	
'Orientation'	Returns a scalar that specifies the angle between the x-axis and the major axis of the ellipse that has the same second-moments as the region.

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203400835)

I think we need code like this one: http://opencvpython.blogspot.nl/2012/04/contour-features.html

This code actually uses fitEllipse, so that might work, thanks!

---

@elboyran commented on [Wed Mar 30 2016](https://github.com/NLeSC/LargeScaleImaging/issues/21#issuecomment-203408585)

it seems it might be as simple as
 (x,y),(MA,ma),angle = cv2.fitEllipse(cnt)

**Comment by dafnevk** [comment]
If I run the current implementation on some regions I found, I get the following error:
`    247 
    248         # fit an ellipse to the contour
--> 249         (x, y), (MA, ma), angle = cv2.fitEllipse(cnt)
    250        # print "x,y: ", x, y
    251         # ellipse parameters

error: /home/dafne/OpenCV/opencv-3.1.0/modules/imgproc/src/shapedescr.cpp:350: error: (-201) There should be at least 5 points to fit the ellipse in function fitEllipse`

**Comment by dafnevk** [comment]
Actually, the bug still exists. find_contours sometimes finds contours of only 4 pixels, I don't know why this is happening, I will make a separate bug for that.

Also, the function was overwriting

**Comment by elboyran** [comment]
Merged with issue #5. Which has been removed as it is redundant.

**Comment by elboyran** [comment]
Merged with issue #21. The latter is closed as it's redundant.
