### ISSUE TITLE
Write test for SalientDetector

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/SalientDetector-python#7]
@dafnevk commented on [Thu Mar 24 2016](https://github.com/NLeSC/LargeScaleImaging/issues/20)

Write tests for the function get_salient_regions_color in the module salientregiondetector, which should test the detection of salient regions for color images.

---

@dafnevk commented on [Thu Mar 31 2016](https://github.com/NLeSC/LargeScaleImaging/issues/20#issuecomment-203827114)

This function is now called get_salient_regions.

---

@dafnevk commented on [Fri Apr 08 2016](https://github.com/NLeSC/LargeScaleImaging/issues/20#issuecomment-207330538)

Now we have the SalientDetector class: we need to write tests for the method detect.

**Comment by elboyran** [comment]
Is this issue overlapping with issues #23 and #24 ?

**Comment by dafnevk** [comment]
Yes, this issue becomes obsolete.
